dailyfinancepulse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('financenews.urls'), name='financenews_urls'),
    path('accounts/', include('allauth.urls')),
]

financenews/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.PostList.as_view(), name='home'), 
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>/', views.PostLike.as_view(), name='post_like'),
]

financenews/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Status choices for the Post model
STATUS = ((0, "Draft"), (1, "Published"))

class Post(models.Model):
    # Title of the blog post, which is unique for each post
    title = models.CharField(max_length=200, unique=True)

    # A URL-friendly slug, unique for each post
    slug = models.SlugField(max_length=200, unique=True)

    # The author of the post, linked to Django's built-in User model
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )

    # The image associated with the post, stored in Cloudinary
    featured_image = CloudinaryField('image', default='placeholder')

    # A short excerpt or summary of the blog post
    excerpt = models.TextField(blank=True)

    # Auto-updated field every time the post is saved
    update_on = models.DateTimeField(auto_now=True)

    # Main body of the blog post
    content = models.TextField()

    # Timestamp for when the post was created
    created_on = models.DateTimeField(auto_now_add=True)

    # The current status of the post (e.g., Draft or Published)
    status = models.IntegerField(choices=STATUS, default=0)

    # ManyToMany field to track which users liked the post
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        # Orders posts so that the most recent is displayed first
        ordering = ["-created_on"]

    def __str__(self):
        # Returns the title when the model instance is converted to a string
        return self.title
    
    # Method to count the number of approved comments for the post
    def number_of_comments(self):
        #Returns the number of approved comments for this post.
        return self.comments.filter(approved=True).count()

    def number_of_likes(self):
        # Counts and returns the number of likes for the post
        return self.likes.count()

class Comment(models.Model):
    # Linking each comment to a specific post
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")

    # Commenter's name
    name = models.CharField(max_length=80)

    # Commenter's email
    email = models.EmailField()

    # Text content of the comment
    body = models.TextField()

    # Automatic timestamp for when comment is made
    created_on = models.DateTimeField(auto_now_add=True)

    # Flag for whether a comment is approved to show
    approved = models.BooleanField(default=False)

    class Meta:
        # Sort comments by the time they were created
        ordering = ["created_on"]

    def __str__(self):
        # String representation showing part of comment and commenter's name
        return f"Comment '{self.body[:20]}...' by {self.name}"
    
    
    

    

financenews/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

financenews/views.py
# Import necessary modules and classes
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from django.http import HttpResponseRedirect, JsonResponse
from .models import Post
from .forms import CommentForm

# Define a view to list blog posts
class PostList(generic.ListView):
    model = Post  # Specify the model to be used for the list view
    queryset = Post.objects.filter(status=1).order_by("-created_on")  # Retrieve published posts
    template_name = "index.html"  # Set the HTML template for the list view
    paginate_by = 6  # Limit the number of posts per page for pagination

# Define a view to display a single blog post along with its comments
class PostDetail(View):
    def get(self, request, slug, *args, **kwargs):
        # Retrieve all published posts
        queryset = Post.objects.filter(status=1)

        # Get the specific post based on the provided slug; return 404 if not found or not published.
        post = get_object_or_404(queryset, slug=slug)

        # Retrieve all approved comments for the post, sorted from newest to oldest.
        comments = post.comments.filter(approved=True).order_by("-created_on")

        # Check if the current logged-in user has liked this post.
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        # Render the post detail template, passing the post, its comments, and a new comment form.
        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": False,
                "liked": liked,
                "comment_form": CommentForm()
            },
        )
        
    def post(self, request, slug, *args, **kwargs):
        # Retrieve all published posts
        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = post.comments.filter(approved=True).order_by("-created_on")
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        # Create a comment form instance with the submitted POST data.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Set email and name for the comment from the logged-in user
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            # Create a new comment object from the form but don't save it to the database yet.
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
            # Reset the comment form after a successful submission
            comment_form = CommentForm()
        else:
            # Comment form is not valid, keep the existing form for user correction
            pass

        # Render the post detail template with updated information
        return render(
            request,
            "post_detail.html",
            {
                "post": post,
                "comments": comments,
                "commented": True,
                "comment_form": comment_form,
                "liked": liked
            },
        )

# Define a view to handle liking and unliking a blog post
class PostLike(View):
    def post(self, request, slug, *args, **kwargs):
        # Retrieve the post based on the given slug. If not found, return a 404 error.
        post = get_object_or_404(Post, slug=slug)

        # Initialize the 'liked' flag as False.
        liked = False

        # Check if the current user has already liked the post.
        if post.likes.filter(id=request.user.id).exists():
            # If yes, remove the user from the post's 'likes' and set 'liked' as False.
            post.likes.remove(request.user)
        else:
            # If not, add the user to the post's 'likes' and set 'liked' as True.
            post.likes.add(request.user)
            liked = True

        # Return a JSON response with the 'liked' status and the updated like count.
        # This allows the client-side script to update the UI without reloading the page.
        return JsonResponse({"liked": liked, "likes_count": post.likes.count()})

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <title>DailyFinancePulse!</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!-- Viewport -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Favicon from Cloudinary -->
    <link rel="icon" type="image/png" href="https://res.cloudinary.com/drqluthko/image/upload/v1706178341/hgx0rbz0grnlf8nbeyls.png">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- FontAwesome Kit -->
    <script src="https://kit.fontawesome.com/4912cd7289.js" crossorigin="anonymous"></script>
</head>


<body class="d-flex flex-column h-100 main-bg">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <!-- Navbar Brand with Logo from Cloudinary -->
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="https://res.cloudinary.com/drqluthko/image/upload/v1706178341/glwl3kolxrmfnddzqhyh.png" alt="DailyFinancePulse Logo" height="100">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
                <span class="navbar-text text-muted">
                    Your Source for Financial Insights and Updates
                </span>
            </div>
        </div>
    </nav>

    <!-- Messages Section -->
    <div class="container mt-4"> 
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <!-- Main Content -->
    <main class="flex-grow-1 main-bg">
        {% block content %}
        <!-- Dynamic content will be inserted here -->
        {% endblock content %}
    </main>

<!-- Footer -->
<footer id="social-networks" class="dark-bg" style="margin-top: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2 class="mb-4">Website created by</h2>
                <a href="https://zerocool989.github.io/porfolio-project-1/" target="_blank" class="text-white">
                    Almir Dumisic - Full Stack Developer, Code Institute Student
                </a>
            </div>
            <div class="col-md-6">
                <h2 class="mb-4">Social Networks</h2>
                <ul class="social-networks">
                    <li>
                        <a href="https://www.linkedin.com/in/almir-dumisic/" target="_blank">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.xing.com/profile/Almir_Dumisic/cv?back_to=mehub" target="_blank">
                            <i class="fa-brands fa-xing"></i>
                        </a>
                    </li>
                    <li>
                        <a href="https://github.com/ZeroCool989" target="_blank">
                            <i class="fa-brands fa-github"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
    <!-- Script to Auto-Close Alert Messages After 3 Seconds -->
    <script>
        document.addEventListener('DOMContentLoaded', function() { 
            let alerts = document.querySelectorAll('.alert');
            alerts.forEach(function(alert) {
                setTimeout(function() {
                    new bootstrap.Alert(alert).close();
                }, 3000);
            });
        });
    </script>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<!-- Main container for the content -->
<div class="container-fluid">
    <div class="row">
        <!-- Primary column for blog entries -->
        <div class="col-12 mt-3 left">
            <!-- Loop through each post in the post list -->
            <div class="row">
                {% for post in post_list %}
                <!-- Blog post card, using Bootstrap grid system -->
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <!-- Image container for the blog post -->
                            <div class="image-container">
                                <!-- Display the featured image of the post -->
                                <img class="card-img-top fixed-image-height" src="{{ post.featured_image.url }}">
                                <!-- Overlay with author information -->
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <!-- Link to the detailed post page -->
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h2 class="card-title">{{ post.title }}</h2>
                                <p class="card-text">{{ post.excerpt }}</p>
                            </a>
                            <hr />
                            <!-- Post metadata (date, likes, and comments) -->
                            <p class="card-text text-muted h6">
                                {{ post.created_on }} <i class="far fa-heart"></i> {{ post.number_of_likes }}
                                <br>
                                <i class="far fa-comments"></i> {{ post.number_of_comments }} comments
                            </p>
                        </div>
                    </div>
                </div>
                <!-- New row for every three posts for layout purposes -->
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Pagination navigation -->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <!-- Previous page link -->
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            <!-- Next page link -->
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

templates/mfa/authenticate.html
{% extends "mfa/base_entrance.html" %}
{% load i18n %}
{% load allauth %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    {% url 'mfa_authenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Sign In" %}
            {% endelement %}
            {% url "account_login" as login_url %}
            {% element button href=login_url tags="secondary,mfa,cancel" %}
                {% trans "Cancel" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

templates/mfa/base_entrance.html
{% extends "allauth/layouts/entrance.html" %}

templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}

templates/mfa/index.html
{% extends "mfa/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="mfa,index" %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% if "totp" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Authenticator App" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.totp %}
                    <p>{% translate "Authentication using an authenticator app is active." %}</p>
                {% else %}
                    <p>{% translate "An authenticator app is not active." %}</p>
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% url 'mfa_deactivate_totp' as deactivate_url %}
                {% url 'mfa_activate_totp' as activate_url %}
                {% if authenticators.totp %}
                    {% element button href=deactivate_url tags="danger,delete,panel" %}
                        {% translate "Deactivate" %}
                    {% endelement %}
                {% else %}
                    {% element button href=activate_url tags="panel" %}
                        {% translate "Activate" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "recovery_codes" in MFA_SUPPORTED_TYPES %}
        {% with total_count=authenticators.recovery_codes.generate_codes|length unused_count=authenticators.recovery_codes.get_unused_codes|length %}
            {% element panel %}
                {% slot title %}
                    {% translate "Recovery Codes" %}
                {% endslot %}
                {% slot body %}
                    {% if authenticators.recovery_codes %}
                        <p>
                            {% blocktranslate count unused_count=unused_count %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
                        </p>
                    {% else %}
                        <p>{% translate "No recovery codes set up." %}</p>
                    {% endif %}
                {% endslot %}
                {% if is_mfa_enabled %}
                    {% if authenticators.recovery_codes %}
                        {% if unused_count > 0 %}
                            {% slot actions %}
                                {% url 'mfa_view_recovery_codes' as view_url %}
                                {% element button href=view_url tags="panel" %}
                                    {% translate "View" %}
                                {% endelement %}
                            {% endslot %}
                            {% slot actions %}
                                {% url 'mfa_download_recovery_codes' as download_url %}
                                {% element button href=download_url tags="secondary,panel" %}
                                    {% translate "Download" %}
                                {% endelement %}
                            {% endslot %}
                        {% endif %}
                    {% endif %}
                    {% slot actions %}
                        {% url 'mfa_generate_recovery_codes' as generate_url %}
                        {% element button href=generate_url tags="secondary,panel" %}
                            {% translate "Generate" %}
                        {% endelement %}
                    {% endslot %}
                {% endif %}
            {% endelement %}
        {% endwith %}
    {% endif %}
{% endblock content %}

templates/mfa/reauthenticate.html
{% extends "account/base_reauthenticate.html" %}
{% load i18n %}
{% load allauth %}
{% block reauthenticate_content %}
    <p>{% blocktranslate %}Enter an authenticator code:{% endblocktranslate %}</p>
    {% url 'mfa_reauthenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
            {% if redirect_field_value %}
                <input type="hidden"
                       name="{{ redirect_field_name }}"
                       value="{{ redirect_field_value }}" />
            {% endif %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Confirm" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock %}

templates/mfa/recovery_codes/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/totp/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}

templates/post_detail.html
{% extends 'base.html' %}

{% block content %}
<!-- Masthead section displaying post title and information -->
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Displaying the post title -->
                <h1 class="post-title">{{ post.title }}</h1>
                <!-- Displaying the post author and creation date -->
                <p class="post-subtitle">{{ post.author }} | {{ post.created_on }}</p>
            </div>
            <!-- Displaying the post's featured image -->
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in post.featured_image.url %}
                <!-- Placeholder image if no featured image is available -->
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <!-- Featured image of the post -->
                <img src="{{ post.featured_image.url }}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Main content container with Likes and Comments Counters -->
<div class="container">
    <div class="row">
        <!-- Blog post content area -->
        <div class="col-lg-8 col-md-10 card mb-4 mt-3 mx-auto">
            <div class="card-body">
                <!-- Displaying the main content of the post -->
                <p class="card-text">{{ post.content | safe }}</p>

                <!-- Likes and comments counters -->
                <div class="mt-4 d-flex justify-content-start align-items-center">
                    <strong>
                        {% if user.is_authenticated %}
                        <button type="button" class="btn-like me-2" data-post-slug="{{ post.slug }}" aria-label="{% if liked %}Unlike{% else %}Like{% endif %}">
                            {% if liked %}
                            <i class="fas fa-heart"></i>
                            {% else %}
                            <i class="far fa-heart"></i>
                            {% endif %}
                        </button>
                        <span class="text-secondary me-3" id="like-count-{{ post.slug }}">{{ post.number_of_likes }}</span>
                        {% else %}
                        <span class="text-secondary me-2"><i class="far fa-heart"></i></span>
                        {% endif %}
                    </strong>
                    <strong class="text-secondary">
                        <i class="far fa-comments me-1"></i> {{ post.comments.count }}
                    </strong>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Comments and Leave a Comment Section -->
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <!-- Comments Section on the Left -->
                        <div class="col-md-8">
                            <h3 class="mt-3">Comments:</h3>
                            <div class="card-body" id="comments-container">
                                <!-- Loop through each comment -->
                                {% for comment in comments %}
                                <div class="comment-item {% if forloop.counter > 3 %}d-none extra-comments{% endif %}" style="padding: 10px;">
                                    <!-- Displaying commenter's name and comment date -->
                                    <p class="comment-header">
                                        {{ comment.name }}
                                        <span class="text-muted">{{ comment.created_on }}</span> wrote:
                                    </p>
                                    <!-- Displaying the comment body -->
                                    <div class="comment-body">
                                        {{ comment.body | linebreaks }}
                                    </div>
                                </div>
                                {% endfor %}
                                {% if comments|length > 3 %}
                                <button id="toggle-comments" class="btn btn-primary mt-3">Show More</button>
                                {% endif %}
                            </div>
                        </div>

                        <!-- Leave a Comment Section in the Center -->
                        <div class="col-md-4 d-flex justify-content-center align-items-center">
                            <div class="card comment-form">
                                <div class="card-body">
                                    {% if commented %}
                                    <div class="alert alert-success" role="alert">
                                        Your comment is awaiting approval
                                    </div>
                                    {% endif %}
                                    {% if user.is_authenticated %}
                                    <h3>Leave a comment:</h3>
                                    <form method="post" class="comment-form" data-post-slug="{{ post.slug }}">
                                        {% csrf_token %}
                                        <!-- Removed the "Your Name" label and input field -->
                                        <label for="id_body">Leave a comment here ;)</label>
                                        <textarea name="body" id="id_body" required></textarea>
                                        
                                        <button type="submit" class="btn btn-primary btn-lg" style="margin-top: 10px;">Submit</button>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- JavaScript for Toggle Comments Button -->
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const toggleButton = document.getElementById('toggle-comments');
        toggleButton?.addEventListener('click', function() {
            document.querySelectorAll('.extra-comments').forEach(comment => {
                comment.classList.toggle('d-none');
            });
            toggleButton.textContent = toggleButton.textContent === 'Show More' ? 'Show Less' : 'Show More';
        });
    });
</script>

<!-- JavaScript for AJAX Like Button -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('.btn-like').forEach(button => {
            button.addEventListener('click', function(e) {
                e.preventDefault();
                const postId = this.getAttribute('data-post-slug');
                fetch(`/like/${postId}/`, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': getCookie('csrftoken'),
                        'Content-Type': 'application/json'
                    }
                })
                .then(response => response.json())
                .then(data => {
                    if (data.liked) {
                        this.innerHTML = '<i class="fas fa-heart"></i>';
                    } else {
                        this.innerHTML = '<i class="far fa-heart"></i>';
                    }
                    document.getElementById(`like-count-${postId}`).textContent = data.likes_count;
                });
            });
        });
    });
    
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
</script>

{% endblock content %}

templates/usersessions/base_manage.html
{% extends "allauth/layouts/manage.html" %}